{
	"version": 1732187050,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/particles.png",
		"images/sprite11-sheet0.png",
		"images/tiledbackground.png",
		"media/whack_1.m4a",
		"media/whack_1.ogg",
		"media/whack_2.m4a",
		"media/whack_2.ogg",
		"media/puch 1.m4a",
		"media/puch 1.ogg",
		"media/puch 2.m4a",
		"media/puch 2.ogg",
		"media/puch 3.m4a",
		"media/puch 3.ogg",
		"media/puch 4.m4a",
		"media/puch 4.ogg",
		"media/level up.m4a",
		"media/level up.ogg",
		"media/pop 1.m4a",
		"media/pop 1.ogg",
		"media/pop 2.m4a",
		"media/pop 2.ogg",
		"media/apt - edit 1.m4a",
		"media/apt - edit 1.ogg",
		"media/tyson meme game.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}